// <auto-generated />
namespace AcunMedyaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig14022025 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig14022025));
        
        string IMigrationMetadata.Id
        {
            get { return "202502142030530_mig14022025"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
