// <auto-generated />
namespace AcunMedyaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig0602252043patientcomment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig0602252043patientcomment));
        
        string IMigrationMetadata.Id
        {
            get { return "202502061748564_mig0602252043patientcomment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
