// <auto-generated />
namespace AcunMedyaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig090220251818ımgurldepart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig090220251818ımgurldepart));
        
        string IMigrationMetadata.Id
        {
            get { return "202502091519233_mig090220251818ımgurldepart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
